// Mercedes Studio is a full-history copy of the upstream dashboard (26 Sep 2026). A leftover "Sheila",
// "A Sheila Bruce Affair" handle or the old owner's address in copy, guides, fixtures or seeds
// is the wrong woman's name on her dashboard, in her emails or in her media kit.
// Scope: every tracked text file under the roots below. Git history, docs/ (BUILD_PLAN's
// copied-from line, YOUTUBE.md's how-we-know proofs) and help/screenshots (regenerated by a job)
// are not scanned. migrations/0001_init.sql is history too (never edited); 0018_mercedes_owner.sql
// moves its seed and must exist.
import { readFile } from "node:fs/promises";
import { execSync } from "node:child_process";
import path from "node:path";

const ROOTS = ["app/", "worker/", "shared/", "help/guides/", "help/index.json", "README.md", "jobs/", "tests/", "migrations/", "index.html", "wrangler.jsonc", "RUNBOOK.md", "CLAUDE.md"];
const PATTERN = /sheila|asheilabruceaffair/i;
// History that is allowed to say the old name.
const ALLOW = new Set(["migrations/0001_init.sql", "migrations/0018_mercedes_owner.sql"]);
// Identifiers of resources this repo really shares with the upstream dashboard. They are named
// after her and cannot be renamed from here (a vault entry, a Google Cloud project and its API
// key's display name, the upstream repo path). Only these exact strings pass; any other use of
// the name on the same line still fails. Adding to this list needs the resource to exist under
// that name (RUNBOOK → Secrets says which); it is never a place for copy.
const SHARED_IDS = [
  "sheila-youtube-api-key",
  "sheila-hunter-api-key",
  "sheila-resend-api-key", // the Resend account both dashboards send from (RUNBOOK → Secrets, 26 Sep 2026)
  "sheilastudio-staging-p0",
  "seq23/sheila-creator-dashboard",
  "Sheila Studio YouTube public stats",
  "no-sheila", // this validator's own name is not her name
];
const BINARY = /\.(png|jpg|jpeg|gif|mp4|mov|webp|ico|woff2?|pdf|zip)$/i;
const MUST_EXIST = "migrations/0018_mercedes_owner.sql";

export default async function ({ root }) {
  const tracked = execSync("git ls-files", { cwd: root, encoding: "utf8" }).split("\n").filter(Boolean);
  const files = tracked.filter((f) => ROOTS.some((r) => (r.endsWith("/") ? f.startsWith(r) : f === r))).filter((f) => !BINARY.test(f) && !f.startsWith("help/screenshots/"));
  const problems = [];
  if (!tracked.includes(MUST_EXIST)) problems.push(`${MUST_EXIST} is missing: 0001_init.sql seeds the media kit link as 'sheila' and only a new migration may move it`);
  if (tracked.includes("public/assets/brand/sheila-logo.png")) problems.push("public/assets/brand/sheila-logo.png: the old logo file is still shipped; the mark is /assets/brand/mercedes-logo.{svg,png}");
  let items = 0;
  for (const f of files) {
    if (ALLOW.has(f)) continue;
    const text = await readFile(path.join(root, f), "utf8").catch(() => null);
    if (text === null) continue;
    items++;
    const lines = text.split("\n");
    const hits = [];
    lines.forEach((line, i) => {
      const stripped = SHARED_IDS.reduce((l, id) => l.split(id).join(""), line);
      if (PATTERN.test(stripped)) hits.push(i + 1);
    });
    for (const n of hits.slice(0, 5)) problems.push(`${f}:${n}: says Sheila; this is Mercedes Studio`);
    if (hits.length > 5) problems.push(`${f}: ${hits.length - 5} more`);
  }
  return { items, problems };
}
