// Mercedes Studio is a full-history copy of Sheila Studio (26 Sep 2026). A leftover "Sheila",
// "A Sheila Bruce Affair" handle or the old owner's address in copy, guides, fixtures or seeds
// is the wrong woman's name on her dashboard, in her emails or in her media kit.
// Scope: every tracked text file under the roots below. Git history, docs/ (BUILD_PLAN's
// copied-from line, YOUTUBE.md's how-we-know proofs) and help/screenshots (regenerated by a job)
// are not scanned. migrations/0001_init.sql is history too (never edited); 0018_mercedes_owner.sql
// moves its seed and must exist.
import { readFile } from "node:fs/promises";
import { execSync } from "node:child_process";
import path from "node:path";

const ROOTS = ["app/", "worker/", "shared/", "help/guides/", "help/index.json", "README.md", "jobs/", "tests/", "migrations/", "index.html", "wrangler.jsonc", "RUNBOOK.md", "CLAUDE.md"];
const PATTERN = /sheila|asheilabruceaffair/i;
// History that is allowed to say the old name.
const ALLOW = new Set(["migrations/0001_init.sql", "migrations/0018_mercedes_owner.sql"]);
// Owned by the sibling rename PRs (brand: styles, email templates, logo block; infra: Worker/D1/R2
// names in config and the tests that pin them). Remove each entry as its PR lands; an entry
// that is already clean is a problem, so the list cannot linger.
const PENDING_SIBLING = new Set([
  "app/styles/global.css",
  "app/styles/mediakit.css",
  "app/styles/tokens.css",
  "app/components/Shell.tsx",
  "worker/services/email.ts",
  "tests/unit/auth-mode.test.ts",
  "tests/unit/legal-pages.test.ts",
  "tests/unit/staging-env.test.ts",
  "tests/live/helpers.ts",
  "tests/e2e/demo.ts",
  "tests/e2e/helpers.ts",
  "tests/e2e/serve.sh",
  "wrangler.jsonc",
  "RUNBOOK.md",
  "CLAUDE.md",
]);
const BINARY = /\.(png|jpg|jpeg|gif|mp4|mov|webp|ico|woff2?|pdf|zip)$/i;
const MUST_EXIST = "migrations/0018_mercedes_owner.sql";

export default async function ({ root }) {
  const tracked = execSync("git ls-files", { cwd: root, encoding: "utf8" }).split("\n").filter(Boolean);
  const files = tracked.filter((f) => ROOTS.some((r) => (r.endsWith("/") ? f.startsWith(r) : f === r))).filter((f) => !BINARY.test(f) && !f.startsWith("help/screenshots/"));
  const problems = [];
  if (!tracked.includes(MUST_EXIST)) problems.push(`${MUST_EXIST} is missing: 0001_init.sql seeds the media kit link as 'sheila' and only a new migration may move it`);
  let items = 0;
  for (const f of files) {
    if (ALLOW.has(f)) continue;
    const text = await readFile(path.join(root, f), "utf8").catch(() => null);
    if (text === null) continue;
    items++;
    const lines = text.split("\n");
    const hits = [];
    lines.forEach((line, i) => {
      if (PATTERN.test(line.replace(/no-sheila/g, ""))) hits.push(i + 1); // this validator's own name is not her name
    });
    if (PENDING_SIBLING.has(f)) {
      if (!hits.length) problems.push(`${f}: clean now; remove it from PENDING_SIBLING in scripts/validators/no-sheila.mjs`);
      continue;
    }
    for (const n of hits.slice(0, 5)) problems.push(`${f}:${n}: says Sheila; this is Mercedes Studio`);
    if (hits.length > 5) problems.push(`${f}: ${hits.length - 5} more`);
  }
  return { items, problems };
}
